RouteList Sorting for API<24
jellyfin/cordova-plugin-chromecast pull request #44
Opened 2019-09-12 10:12 UTC by pgcan

Issue #43

2019-09-12 20:30 UTC, anthonylavado approved these changes

2019-09-12 20:48 UTC, emilsas requested changes
The same typo in Rout as in PR #45

2019-09-12 20:51 UTC, thornbill commented on src/android/Chromecast.java
> +					routeList.sort(Comparator.comparing(RouteInfo::getName));
Is there a performance gain or something to warrant keeping both of these? If `Collections.sort` will cover all (supported) SDK versions I would just go with that method instead of keeping both.

2019-09-12 20:52 UTC, anthonylavado requested changes
See other comments.

2019-09-13 05:09 UTC, pgcan commented on src/android/Chromecast.java
> +					routeList.sort(Comparator.comparing(RouteInfo::getName));
Collections.Sort is recommended for ArrayList. Found it on SO. 
https://stackoverflow.com/a/5208144/1613632

2019-09-15 04:24 UTC, anthonylavado approved these changes

2019-09-15 04:24 UTC, merged